product_arr=[
    {
        product_id:90,
        product_name:"Trouser",
        product_price:20,
        product_rating:4
    },
    {
        product_id:23,
        product_name:"Leather",
        product_price:20,
        product_rating:4
    },
    {
        product_id:80,
        product_name:"Leather",
        product_price:20,
        product_rating:4
    },
    {
        product_id:90,
        product_name:"Leather",
        product_price:20,
        product_rating:4
    },
    {
        product_id:90,
        product_name:"Trouser",
        product_price:20,
        product_rating:4
    },
    {
        product_id:90,
        product_name:"Leather",
        product_price:20,
        product_rating:4
    },
    {
        product_id:90,
        product_name:"Leather",
        product_price:20,
        product_rating:4
    },
    {
        product_id:80,
        product_name:"Leather",
        product_price:20,
        product_rating:4
    }
]

module.exports=product_arr;
